@startuml
actor User
actor timeDaemon
User -> timeDaemon
rectangle Website {
    User -- (select Dashboard)
    User -- (select Station)
    (select Station) -- (add Station to selection)
    (select Station) -- (remove Station from selection)
    User -- (select Historical)
    User -- (logout)

    timeDaemon -- (update Charts)
}
@enduml
